name: Test Install Scripts for Buster on Docker

on:
  schedule:
    # run at 5 every sunday
    - cron: '0 5 * * 0'
  push:
    branches-ignore:
      - 'future3/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Build Buster ARMv7
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        push: false
        file: ./ci/Dockerfile.buster.test_install.armv7
        platforms: linux/arm/v7
        tags: rpi-jukebox-rfid-buster:latest
        cache-from: type=gha,scope=${{ github.ref_name }}-buster
        cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-buster
        build-args: |
          GIT_BRANCH=${{ github.ref_name }}
          GIT_URL=${{ github.server_url }}/${{ github.repository }}
          
    - name: Run run_installation_tests.sh Buster ARMv7
      uses: tj-actions/docker-run@v2
      with:
        image: rpi-jukebox-rfid-buster:latest
        options: --platform linux/arm/v7
        name: run_installation_tests.sh
        args: |
          /code/scripts/installscripts/tests/run_installation_tests.sh
          
    - name: Run run_installation_tests2.sh Buster ARMv7
      uses: tj-actions/docker-run@v2
      with:
        image: rpi-jukebox-rfid-buster:latest
        options: --platform linux/arm/v7
        name: run_installation_tests2.sh
        args: |
          /code/scripts/installscripts/tests/run_installation_tests2.sh
          
    - name: Run run_installation_tests3.sh Buster ARMv7
      uses: tj-actions/docker-run@v2
      with:
        image: rpi-jukebox-rfid-buster:latest
        options: --platform linux/arm/v7
        name: run_installation_tests3.sh
        args: |
          /code/scripts/installscripts/tests/run_installation_tests3.sh
