name: Python + Docs Checks and Tests

on:
  push:
    branches:
        - 'future3/**'
    paths:
        - '**.py'
        - '**.py.*'
        - 'docs/sphinx/**'
  pull_request:
    branches:
        - 'future3/**'
    paths:
        - '**.py'
        - '**.py.*'
        - 'docs/sphinx/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev pulseaudio
        python3 -m pip install --upgrade pip
        pip3 install wheel
        pip3 install spidev
        pip3 install -r requirements.txt
        # For operation of the Jukebox, ZMQ must be compiled from sources due to Websocket support
        # When just building the docs, the regular ZMQ package is sufficient
        pip3 install -r docs/sphinx/requirements_pyzmq.txt
        pip3 install -r docs/sphinx/requirements.txt
        # Also install all optional dependencies
        pip3 install -r src/jukebox/components/rfid/hardware/fake_reader_gui/requirements.txt
        pip3 install -r src/jukebox/components/rfid/hardware/pn532_i2c_py532/requirements.txt
        pip3 install -r src/jukebox/components/rfid/hardware/rdm6300_serial/requirements.txt
        pip3 install -r src/jukebox/components/rfid/hardware/rc522_spi/requirements.txt
    - name: Lint with flake8
      run: |
        pip3 install flake8
        # Stop the build if linting fails
        ./run_flake8.sh
    - name: Build the docs
      working-directory: ./docs/sphinx
      run: |
        # Stop the build if documentation cannot be built
        # Treat all warnings as errors
        sphinx-build -W --keep-going -T -a -E -b html . _build
