name: Python + Docs Checks and Tests

on:
  push:
    branches:
        - 'future3/**'
    paths:
        - '**.py'
  pull_request:
    branches:
        - 'future3/**'
    paths:
        - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev pulseaudio
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        # For operation of the Jukebox, ZMQ must be compiled from sources due to Websocket support
        # Also install all optional dependencies
        pip3 install -r src/jukebox/components/rfid/hardware/fake_reader_gui/requirements.txt
        pip3 install -r src/jukebox/components/rfid/hardware/pn532_i2c_py532/requirements.txt
        pip3 install -r src/jukebox/components/rfid/hardware/rdm6300_serial/requirements.txt
        pip3 install -r src/jukebox/components/rfid/hardware/rc522_spi/requirements.txt
    - name: Run pytest with coverage
      run: |
        ./run_pytest.sh --cov --cov-report xml --cov-config=.coveragerc
    - name: Report to Coveralls (parallel)
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: coverage.xml
        format: cobertura
        parallel: true
    - name: Lint with flake8
      run: |
        pip3 install flake8
        # Stop the build if linting fails
        ./run_flake8.sh
    - name: Generate docstring
      run: |
        # If commited docstring is not up to date, this triggers a modified file in git
        ./run_docgeneration.sh
    - name: Check docstring is up to date (if no modified file in git)
      uses: CatChen/check-git-status-action@v1
      with:
        fail-if-not-clean: true 
        push-if-not-clean: false 
        request-changes-if-not-clean: true 
        request-changes-token: ${{ secrets.GITHUB_TOKEN }}
        request-changes-comment: 'Please execute ./run_docgeneration.sh, to ensure docstrings are generated.'
        targets: './documentation/developers/docstring'

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
